### ISSUE TITLE
Missing key_translations

### ISSUE THREAD

**Issue by ArtiVlasov** [uparma/uparma-py#12]
While working on the omssa translations I came along the following code:

`self.params["_omssa_precursor_error"] = (
            float(self.params["translations"]["precursor_mass_tolerance_plus"])
            + float(self.params["translations"]["precursor_mass_tolerance_minus"])
        ) / 2.0`

So far we import default_params via uparma.get_default_params() for all parameters where a key_translation is available for the respective engine. If not, this parameter will not be picked up. Therefore, if `"precursor_mass_tolerance_plus"` & `"precursor_mass_tolerance_minus"` would not be provided by the input dict, this will raise an error.

Looking for the origin of this issue, @MKoesters and I figured out that there are multiple key_translations missing for several engines. E.g. for the `"precursor_mass_tolerance_plus"` there is a list of 22 engines where it is used in ursgal1 and only 6 in uparma. Having a quick chat with Gavain, it became clear that those are all the engines where a 1-1 mapping was not possible. Thus, they were removed to fulfil the compatibility with back and forward formatting.

Thus, the mapping would need to be done in the engine wrappers. In the case of omssa both keys map to `"-te"`, which is assigned the value of `"_omssa_precursor_error"` in the wrapper. However, as mentioned above to calculate this value we need the plus and minus tolerance beforehand. Which we could trust the user to provide (bad idea), or we have to have some default values in place at this point. 

Since this is an issue relevant for quite some engines, we should discuss how we will import these parameters into the wrapper for further "wrapper-specific processing".

My suggestions atm would be:

1. we check in the wrapper if e.g. `self.params["translations"]["precursor_mass_tolerance_plus"]` is available and if not assign to a default value. This would require all the checks & default params in each wrapper. Or,

2. in uparma for those cases we will simply keep the key translation of engine_style = ursgal_style. Thus, the parameter will be imported during get_default_params and we would have a default value directly from the uparma to make the above calculation. Once it is done, it will be mapped to the engine specific key as already implemented in the ursgal1 wrappers.

I feel like both have their pros & cons, but yeah... happy to discuss :) 

P.S. Of course the self.params part will be the currently under revision umeta.udict style ;)

**Comment by StSchulze** [comment]
@fu and I had this discussion before and I'm fairly sure we came to the following conclusion:
In order to allow for a 1 to 1 mapping, those parameters that map onto multiple other parameters (like `-te`) will get a defined suffix (e.g. "_part_1", "_part_2", etc.). The uparma mapper should than include the functionality to map `-te` to all the parameters that have the defined suffix (`-te_part1`, `-te_part_2`, etc). So you would get a list with multiple params back that you can then handle in the wrapper.

As a somewhat related point:
The wrapper should not contain any param names that are not omssa param names, i.e. `precursor_mass_tolerance_plus` should not be part of the wrapper.

**Comment by ArtiVlasov** [comment]
Okay, so it goes into the direction of my 2nd suggestion, right?

In my case with omssa I would add "-te_part1" as key_translation to e.g. "precursor_mass_tolerance_plus" and "-te_part2" to "precursor_mass_tolerance_minus" in uparma and subsequently map the two of them to "-te" in the omssa wrapper.

**Comment by StSchulze** [comment]
Yeah, exactly

**Comment by ArtiVlasov** [comment]
This one can be closed. The convention is - if a key/value translation is missing it should be included in the uparma.lib and subsequently updated in the uparma-py. DO NOT change the parameters.json within the uparma-py ;)
