### ISSUE TITLE
Param value translation

### ISSUE THREAD

**Issue by ArtiVlasov** [uparma/uparma-py#20]
I have a question to the way how parameters are imported into ursgal in regards if or if not a value_translation is available. Basically, if the behaviour I am observing is a bug or a feature ^^ 

Example:

`"_id": 83,
    "default_value": "ppm",
    "description": "Fragment mass tolerance unit: available in ppm (parts-per-millon), da (Dalton) or mmu (Milli mass unit)",
    "key_translations": {
      "ursgal_style_1": "frag_mass_tolerance_unit",
     "xtandem_style_1": "spectrum, fragment monoisotopic mass error units"},
    "value_translation":{"xtandem_style_1": [
        [
          "da",
          "Daltons"
        ]}`

Since there is no value translation for the default value `ppm` when importing the default parameters into the xtandem wrapper the result is:

`'frag_mass_tolerance_unit': {'translated_key': 'spectrum, fragment monoisotopic mass error units',
  'translated_value': {'da': 'Daltons'}}`

Meaning that you actually have to format the param back to 'ppm' in that case in the wrapper.  Thus, I was wondering if this is the intended behaviour, or if it should actually be that if no value_translation defined for the default_value, the default_value will be provided...

It feels rather like a bug to me, but perhaps I am missing some "intended logic" behind this ;)

**Comment by StSchulze** [comment]
That looks wrong to me, should be `'translated_value': 'ppm'` if I'm not completely wrong.

**Comment by ArtiVlasov** [comment]
I think the issue resides here:

https://github.com/uparma/uparma-py/blob/b1b52cb849eb6bfe0d87c8a4dfcf0fc6a7b9dfa6/uparma/uparma.py#L350-L360

The "exception" in line 360 should not be the dict, but basically the `untranslated_default`, or?

**Comment by StSchulze** [comment]
I think that's correct, yes.
Add the example you described above to the tests and give it a try, I would say ;)

**Comment by ArtiVlasov** [comment]
You can examine the bug using the branch `bug/get_default_params` 

The new test in `test_get_default_params/test_get_default_params_with_no_value_trans_for_default`, where `ppm` is wrongly translated to `{'da': 'Daltons'}` fails as expected. 

I will fix it later ;)

**Comment by ArtiVlasov** [comment]
Can be closed as the fix has been merged!
