### ISSUE TITLE
None default value is saved as string

### ISSUE THREAD

**Issue by MKoesters** [uparma/uparma-py#26]
In some parameters, the default value is `"None"`, which is translated to `"None"` instead of `None`
We should either use `null` (which is automagically translated to `None` when reading with the python json library) instead of `None` or convert to boolean in the translate method

**Comment by ArtiVlasov** [comment]
I would go fo changing the "None" to null in the parameters.json

**Comment by MKoesters** [comment]
Fixed here https://github.com/uparma/uparma-lib/pull/32
